### ISSUE TITLE
Package ros-rolling-ur-moveit-config has been removed

### ISSUE THREAD

**Issue by Xi-HHHM** [UniversalRobots/Universal_Robots_ROS2_Ignition_Simulation#5]
Source: https://discourse.ros.org/t/new-packages-for-ros-2-rolling-ridley-2023-01-06/29094

Suggestion: use `ros-rolling-ur-bringup` instead

I can open a PR if needed.

@destogl

**Comment by fmauch** [comment]
That was a temporary issue, closing this.
