### ISSUE TITLE
ur_sim_moveit.launch.py launches two rviz instances

### ISSUE THREAD

**Issue by mrjogo** [UniversalRobots/Universal_Robots_ROS2_Ignition_Simulation#6]
### Affected ROS Driver version(s)

847d052b7c9154905386b6633aaf39e182887740

### Used ROS distribution.

Humble

### What combination of platform is the ROS driver running on.

Linux without realtime patch

### How did you install the UR ROS driver

Build the driver from source and using the UR Client Library from binary

### What robot platform are the driver connected to.

URSim in linux

### Robot SW / URSim version(s)

N/A, running in Gazebo (not an option above)

### How are you using the ROS driver

Others

### Issue details

# Summery
Running `ros2 launch ur_simulation_ignition ur_sim_moveit.launch.py` causes two instances of rviz to launch, when only one should.

## Issue details
`ur_sim_moveit.launch.py` includes `ur_sim_control.launch.py` with `"launch_rviz": "false"`, and `ur_moveit.launch.py` with `"launch_rviz": "true",`. However, two RViz instances are started.

From experimenting, it appears that the `ur_moveit.launch.py` `launch_rviz` argument is somehow leaking into `ur_sim_control.launch.py`. Setting it to `false` causes no instances of rviz to launch. Also, when it is true, commenting out `delay_rviz_after_joint_state_broadcaster_spawner` from `ur_sim_control.launch.py` results in the expected behavior of only the MoveIt RViz being started.

## Steps to Reproduce
Run `ros2 launch ur_simulation_ignition ur_sim_moveit.launch.py`

## Expected Behavior
One RViz launching

## Actual Behavior
Two RViz's

# Workaround Suggestion
Comment out `delay_rviz_after_joint_state_broadcaster_spawner` in `ur_sim_control.launch.py`

### Accept Public visibility

- [X] I agree to make this context public

**Comment by fmauch** [comment]
Same as in https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation/issues/17

**Comment by fmauch** [comment]
For rolling / jazzy this is already fixed, PRs for iron and humble have been created in #27 and its upcoming backport.
