### ISSUE TITLE
Unable to fetch current robot state Moveit2

### ISSUE THREAD

**Issue by SteMuc** [UniversalRobots/Universal_Robots_ROS2_Ignition_Simulation#65]
Morning,

I would like to ask you help regarding the Moveit2 setup with ignition. I'm using ROS2 Humble with ignition gazebo. After launch the ur_sim_moveit.launch.py, i tried to load the move group interface in a cpp node (the example of basic tutorials in the moveit2_tutorials pkg) and i got this error in the terminal when trying to catch the currentRobotPose. 

"unable to fetch the current robot state"

Is there any steps that i forgot or someone has experiences a similar issue?

Thank you very much for your kindly support.

Stefano

**Comment by SteMuc** [comment]
I manage to solve. When you launch a node, you need to pass in the parameters the flag use_sim_time set to True. In this way, I'm able to retrieve the getCurrentPose().pose from the moveit_interface (moveit::planning_interface::MoveGroupInterface group(node, "ur_manipulator);

This is the launch file:

```
from launch import LaunchDescription
from launch_ros.actions import Node
from launch.substitutions import LaunchConfiguration
from launch.actions import DeclareLaunchArgument

def generate_launch_description():
    use_sim_time = LaunchConfiguration("use_sim_time")
    return LaunchDescription([
        DeclareLaunchArgument(
                "use_sim_time",
                default_value="true",
                description="Using or not time from simulation",
            ),
        Node(
            package='planning_utilities_pkg',
            executable='planning_server',
            output='screen',
            parameters=[{
                "use_sim_time": use_sim_time,
            },
        ]
        )
    ])
```

**Comment by urfeex** [comment]
Yes, use_sim_time is important. Glad you solved it yourself. I'll go ahead and close this issue, if you don't mind.
