### ISSUE TITLE
UR not moving with ROS control

### ISSUE THREAD

**Issue by pla10** [UniversalRobots/Universal_Robots_ROS2_Ignition_Simulation#66]
ROS version: Jazzy
Universal_Robots_ROS2_GZ_Simulation commit SHA: cf43d88c5d9688f54e8e173ea27ef88c9c332ebd
OS Version: Ubuntu 24.04 Noble
Gazebo version: Harmonic 8.7.0

![image](https://github.com/user-attachments/assets/6d1a6aae-4cc3-4bda-ba3e-6d01402fda7a)

I am following the steps in the README for the `ur_sim_control.launch.py.` I tried moving the robot as suggested with `ros2 launch ur_robot_driver test_joint_trajectory_controller.launch.py` and also with my own code, but the robot does not move.
I get no error message in the terminals. 
With MoveIt (`ros2 launch ur_simulation_gz ur_sim_moveit.launch.py`) it moves.

**Comment by urfeex** [comment]
Thank you for reporting this. We recently changed the default controller to be the scaled JTC, it seems we didn't update the README accordingly. 

```
ros2 run ur_robot_driver example_move.py
````

should do the trick.

**Comment by pla10** [comment]
Thank you for the quick response! This fixed the issue
